export const ADD_REMOVE_CART = "ADD_REMOVE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";

export const OPEN_DETAILS = "OPEN_DETAILS";
export const CLOSE_DETAILS = "CLOSE_DETAILS";
export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";

export const SET_FILTER_WITH_COLOR = "SET_FILTER_WITH_COLOR";
export const SET_FILTER_WITH_VARIANT = "SET_FILTER_WITH_VARIANT";
export const SET_SORT_BY = "SET_SORT_BY";
export const RESET_FILTERS = "RESET_FILTERS";
export const SET_PAGINATION = "SET_PAGINATION";
